### PR TITLE
Create Payment

### PR DESCRIPTION
**Pull request by Infernoman**
Multipool payment script. Payouts done in bitcoin using the command 'bitcoind sendtoaddress'

### CODE REVIEW

**Comment by sigwo** [comment]
In the spirit of saving tx fees per BTC payout, should we instead use 'bitcoin-cli sendmany'? Also, bitcoind is deprecated for use with the RPC.

**Comment by Infernoman** [comment]
currently its just a loop of each worker, im not sure which format the sendmany takes, so it would have to be put into a list and then sent out with sendmany

**Comment by sigwo** [comment]
Ah ok. Maybe could be an enhancement for later. 

-SG

**Comment by sigwo** [comment]
I'm going through to clean up the folder paths.

**Comment by Infernoman** [comment]
Seems like this has already proven a problem for me, im testing a fix for this now, just want to make sure it is right first.

**Pull request merged**
