### PR TITLE
Update profitSwitch.js

### PR DESCRIPTION
**Pull request by Moxnatiy**
Changed logger.warning to logger.warn (we use the log4js)
I do not quite understand the need for function   process.on('message', function(message)  but it's work

TO DO 
fs.writeFile('~/unomp/website/static/' + algo + '.txt', bestBtcPerMhPerHour.toFixed(8));
dont work correct path if wrong, changed to 
fs.writeFile( + algo + '.txt', bestBtcPerMhPerHour.toFixed(8),function (err) 
file writen in ints.js forder but its NaN.txt , but no error please deal with ways

profitSwitch work  with out errors

### CODE REVIEW

**Comment by sigwo** [comment]
Testing in my local repo. I noticed I missed changing 'warning' to 'warn'. :)

**Comment by sigwo** [comment]
Making that change in my local pool breaks it.

**Comment by sigwo** [comment]
Ah, are you not using the multipooling functions yet?

**Comment by Moxnatiy** [comment]
yes, not use only profitswich

**Comment by Moxnatiy** [comment]
now try lanch with multipooling

**Comment by sigwo** [comment]
reference https://github.com/sigwo/unified-node-open-mining-portal/commit/86d5d71d67fa04ba2584dd1574b66e89c03766f2 

do a git pull and profit switching is operational

**Pull request closed without merging**
